FROM centos
MAINTAINER devops
LABEL 0S=DC
RUN curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
CMD [“chmod”,” +x”,” /usr/local/bin/docker-compose”]

